server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    service-ribbon: /a/**
    service-feign: /b/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    